name: example
description: A simple command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  rand:
    path: ../

dev_dependencies:
  lints: ^6.0.0
