name: rand
description: "Advanced, easy-to-use random generator for Dart. Generate random numbers, text, colors, dates, passwords, and more."
version: 3.0.0
homepage: https://mehmetesen.com
repository: https://github.com/esenmx/rand

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"

dev_dependencies:
  checks: ^0.3.0
  test: ^1.28.0
  very_good_analysis: ^10.0.0
